//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 2014-01-14 8:10:10 PM
namespace VODUnitTest.TV.VOD
{
    
    /// <summary>
    /// There are no comments for VODEntities in the schema.
    /// </summary>
    public partial class VODEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new VODEntities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public VODEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("TV.VODModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("VODUnitTest.TV.VOD", typeName.Substring(11)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("VODUnitTest.TV.VOD", global::System.StringComparison.Ordinal))
            {
                return string.Concat("TV.VODModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Assets in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Asset> Assets
        {
            get
            {
                if ((this._Assets == null))
                {
                    this._Assets = base.CreateQuery<Asset>("Assets");
                }
                return this._Assets;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Asset> _Assets;
        /// <summary>
        /// There are no comments for Assets in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAssets(Asset asset)
        {
            base.AddObject("Assets", asset);
        }
    }
    /// <summary>
    /// There are no comments for TV.VODModel.Asset in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AssetId
    /// AssetName
    /// Description
    /// ProviderId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Assets")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("AssetId", "AssetName", "Description", "ProviderId")]
    public partial class Asset : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Asset object.
        /// </summary>
        /// <param name="assetId">Initial value of AssetId.</param>
        /// <param name="assetName">Initial value of AssetName.</param>
        /// <param name="description">Initial value of Description.</param>
        /// <param name="providerId">Initial value of ProviderId.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Asset CreateAsset(string assetId, string assetName, string description, string providerId)
        {
            Asset asset = new Asset();
            asset.AssetId = assetId;
            asset.AssetName = assetName;
            asset.Description = description;
            asset.ProviderId = providerId;
            return asset;
        }
        /// <summary>
        /// There are no comments for Property AssetId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AssetId
        {
            get
            {
                return this._AssetId;
            }
            set
            {
                this.OnAssetIdChanging(value);
                this._AssetId = value;
                this.OnAssetIdChanged();
                this.OnPropertyChanged("AssetId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AssetId;
        partial void OnAssetIdChanging(string value);
        partial void OnAssetIdChanged();
        /// <summary>
        /// There are no comments for Property AssetName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AssetName
        {
            get
            {
                return this._AssetName;
            }
            set
            {
                this.OnAssetNameChanging(value);
                this._AssetName = value;
                this.OnAssetNameChanged();
                this.OnPropertyChanged("AssetName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AssetName;
        partial void OnAssetNameChanging(string value);
        partial void OnAssetNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ProviderId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProviderId
        {
            get
            {
                return this._ProviderId;
            }
            set
            {
                this.OnProviderIdChanging(value);
                this._ProviderId = value;
                this.OnProviderIdChanged();
                this.OnPropertyChanged("ProviderId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProviderId;
        partial void OnProviderIdChanging(string value);
        partial void OnProviderIdChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
